MOIETIES = {
    # Note that groups are indexed starting from 2
    # 0 index is reserved for padding token
    # Carbon-based groups
    "methyl": "[CX4H3]",
    "secondary_carbon": "[#6X4H2]",
    "tertiary_carbon": "[#6X4H1]",
    "quaternary_carbon": "[#6X4H0]",
    "ethyl": "[CX4H2][CX4H3]",  # Linear alkyl groups
    "n-propyl": "[CX4H2][CX4H2][CX4H3]",
    "n-butyl": "[CX4H2][CX4H2][CX4H2][CX4H3]",
    "n-pentyl": "[CX4H2][CX4H2][CX4H2][CX4H2][CX4H3]",
    "n-hexyl": "[CX4H2][CX4H2][CX4H2][CX4H2][CX4H2][CX4H3]",
    "isopropyl": "[CX4H]([CH3])[CH3]",  # Branched alkyl groups
    "isobutyl": "[CX4H2][CX4H]([CH3])[CH3]",
    "isopentyl": "[CX4H2][CX4H2][CX4H]([CH3])[CH3]",
    "sec-butyl": "[CX4H]([CH3])[CX4H2][CH3]",
    "t-butyl": "[CX4]([CH3])([CH3])[CH3]",
    "t-pentyl": "[CX4]([CH3])([CH3])[CH2][CH3]",
    "alkene": "[CX3]=[CX3]",
    "alkyne": "[CX2]#[CX2]",
    "cyclopropyl": "C1CC1",  # Cycloalkyl groups
    "cyclobutyl": "C1CCC1",
    "cyclopentyl": "C1CCCC1",
    "cyclohexyl": "C1CCCCC1",
    "benzene": "[cR1]1[cR1][cR1][cR1][cR1][cR1]1",
    "benzene_fused": "c12ccccc1cccc2",
    "biphenyl": "c1ccccc1-c1ccccc1",
    # Oxygen-containing groups
    "hydroxyl": "[OX2H]",
    "ether": "[OX2]([#6])[#6]",
    "hydroperoxy": "[OX2H][OX2]",
    "bivalent_oxygen": "[OX2]",
    "peroxy": "[OX2][OX2]",
    "aldehyde": "[CX3H1](=O)[#6]",
    "ketone": "[#6X3](=[OX1])([#6])[#6]",
    "carbonyl": "[C](=O)",
    "carboxylate": "[CX3](=O)[O-]",
    "carboxyl": "[CX3](=O)[OH]",
    "ester": "[#6][CX3](=O)[OX2H0][#6]",
    "hemiacetal": "[OX2H][CX4]([OH])[#6]",
    "acetal": "[OX2]([#6])[CX4]([OX2][#6])[#6]",
    "hemiketal": "[OX2H][CX4]([OX2][#6])([#6])[#6]",
    "ketal": "[OX2]([#6])[CX4]([OX2][#6])([#6])[#6]",
    "orthoester": "[#6][CX4]([OX2][#6])([OX2][#6])[OX2][#6]",
    "oxalate": "OC(=O)C(=O)O",
    "carbonate_ester": "[#6][OX2]C(=O)[OX2][#6]",
    "orthocarbonate_ester": "[#6]OC([OX2][#6])([OX2][#6])[OX2][#6]",
    # Nitrogen-containing groups
    "cyanate": "[NX2]=[CX2]=[OX1]",
    "isocyanate": "[OX1]=[CX2]=[NX2]",
    "amidine": "[#6X3](=[NX2])[NX3]",
    "carbamate": "[NX3][CX3](=[OX1])[OX2][#6]",
    "primary_amine": "[NX3H2][#6]",
    "secondary_amine": "[NX3H1]([#6])[#6]",
    "tertiary_amine": "[NX3]([#6])([#6])[#6]",
    "trivalent_nitrogen": "[N;X3;!#6;!#6;!#6]",
    "amide": "[NX3][CX3](=[OX1])[#6]",
    "imide": "[NX3](C=O)C=O",
    "4_ammonium_ion": "[NX4+]",
    "hydrazone": "[NX3][NX2]=[#6]",
    "primary_ketimine": "[NX2H1]=[#6X3]([#6])[#6]",
    "primary_aldimine": "[NX2H1]=[CX3H1][#6]",
    "secondary_ketimine": "[NX2]=[#6X3]([#6])[#6]",
    "secondary_aldimine": "[NX2]=[CX3H1][#6]",
    "nitrile": "[NX1]#[CX2]",
    "azide": "[#6]-[NX2]=[NX2+]=[NX1-]",
    "azo": "[#6]-[NX2]=[NX2]-[#6]",
    "nitrite": "[N;X2](=O)[O;X2]",
    "nitrate_ester": "[#6]-O-[N+](=O)[O-]",
    "nitrate_ion": "[N+](=O)([O-])[O-]",
    "isonitrile": "[CX1-]#[NX2+]",
    "nitrosooxy": "[#6]-O-N=O",
    "nitro": "[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]",
    "nitroso": "[NX2]=O",
    "aldoxime": "[CX3H1](=N[OX2H])[#6]",
    "ketoxime": "[#6X3](=[NX2][OX2H])[#6]",
    # Sulfur-containing groups
    "sulfhydryl": "[SX2H]",
    "sulfide": "[SX2;!$([S-])]",
    "sulfite": "[S](=O)([O])[O]",
    "disulfide": "[SX2;!$([S-])][SX2;!$([S-])]",
    "trisulfide": "[SX2;!$([S-])][SX2;!$([S-])][SX2;!$([S-])]",
    "sulfinyl": "[#6][SX3](=O)[#6]",
    "sulfonyl": "[#6][SX4](=O)(=O)[#6]",
    "sulfur_dioxide": "O=S=O",
    "sulfuric_acid": "[OX2H][SX4](=O)(=O)[OX2H]",
    "sulfino": "[SX3](=O)[OX2H]",
    "sulfonic_acid": "[#6][SX4](=O)(=O)[OX2H]",
    "sulfonate_ester": "[#6][SX4](=O)(=O)[OX2][#6]",
    "thiocyanate": "[SX2][CX2]#[NX1]",
    # Phosphorus-containing groups
    "phosphino": "[PX3]([#6])[#6]",
    "phosphono": "[PX4](=O)([OX2H])([OX2H])[OX2H]",
    "phosphate": "[PX4](=O)([OX2][#6])([OX2][#6])[OX2][#6]",
    "phosphodiester": "[PX4](=O)([OX2][#6])([OX2][#6])[OX2H]",
    "phosphoryl": "[P](=O)",
    # Boron-containing groups
    "borono": "[BX3]([OX2H])([OX2H])",
    "boronate": "[BX3]([OX2][#6])([OX2][#6])",
    "borino": "[BX2H]([#6])",
    "borinate": "[BX3H]([#6])[#6]",
    "trigonal_borate": "[BX3](O)(O)O",
    "tetra_borate": "[BX4](O)(O)(O)O",
    # Silicon-containing groups
    "silyl_ether": "[#6][SiX4]([#6])([#6])[OX2][#6]",
    "dichlorosilane": "[SiX4H2](Cl)Cl",
    "trimethylsilyl": "[SiX4]([#6])([#6])[#6]",
    "dimethylsilyl": "[SiX3]([#6])([#6])",
    "dimethoxysilyl": "[SiX4](OC)(OC)",
    # Halogens
    "fluoro": "[FX1]",
    "chloro": "[ClX1]",
    "bromo": "[BrX1]",
    "iodo": "[IX1]",
    # Halogen-containing groups
    "haloformyl": "[CX3](=[OX1])[FX1,ClX1,BrX1,IX1]",
    "trifluoromethyl": "[CX4](F)(F)F",
    "difluorochloromethyl": "[CX4](F)(F)Cl",
    "bromodifluoromethyl": "[CX4](F)(F)Br",
    "trichloromethyl": "[CX4](Cl)(Cl)Cl",
    "bromodichloromethyl": "[CX4](Cl)(Cl)Br",
    "tribromomethyl": "[CX4](Br)(Br)Br",
    "dibromofluoromethyl": "[CX4](Br)(Br)F",
    "triiodomethyl": "[CX4](I)(I)I",
    "difluoromethyl": "[CX4](F)F",
    "fluorochloromethyl": "[CX4H2](F)Cl",
    "dichloromethyl": "[CX4H2](Cl)Cl",
    "chlorobromomethyl": "[CX4H2](Cl)Br",
    "chloroiodomethyl": "[CX4H2](Cl)I",
    "dibromomethyl": "[CX4H2](Br)Br",
    "bromoiodomethyl": "[CX4H2](Br)I",
    "diiodomethyl": "[CX4H2](I)I",
    # Ionic groups
    "arsenide_ion": "[As-]",
    "boride_ion": "[B-]",
    "lithium_cation": "[Li+]",
    "nitrogen_cation": "[N+]",
    "nitrogen_anion": "[N-]",
    "oxygen_anion": "[O-]",
    "phosphorus_anion": "[P-]",
    "sulfur_anion": "[S-]",
    "chlorine(III) cation": "[Cl+3X4]",
}
